/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FranchiseeStore } from "./FranchiseeStore";
import { FranchiseeStoreCountArgs } from "./FranchiseeStoreCountArgs";
import { FranchiseeStoreFindManyArgs } from "./FranchiseeStoreFindManyArgs";
import { FranchiseeStoreFindUniqueArgs } from "./FranchiseeStoreFindUniqueArgs";
import { DeleteFranchiseeStoreArgs } from "./DeleteFranchiseeStoreArgs";
import { FranchiseeStoreService } from "../franchiseeStore.service";
@graphql.Resolver(() => FranchiseeStore)
export class FranchiseeStoreResolverBase {
  constructor(protected readonly service: FranchiseeStoreService) {}

  async _franchiseeStoresMeta(
    @graphql.Args() args: FranchiseeStoreCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FranchiseeStore])
  async franchiseeStores(
    @graphql.Args() args: FranchiseeStoreFindManyArgs
  ): Promise<FranchiseeStore[]> {
    return this.service.franchiseeStores(args);
  }

  @graphql.Query(() => FranchiseeStore, { nullable: true })
  async franchiseeStore(
    @graphql.Args() args: FranchiseeStoreFindUniqueArgs
  ): Promise<FranchiseeStore | null> {
    const result = await this.service.franchiseeStore(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FranchiseeStore)
  async deleteFranchiseeStore(
    @graphql.Args() args: DeleteFranchiseeStoreArgs
  ): Promise<FranchiseeStore | null> {
    try {
      return await this.service.deleteFranchiseeStore(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
